### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by pasine** [timanrebel/HockeyApp#13]
I am trying to use this module but whenever I add it to my app, the build fails with this error:  

Building with Titanium SDK 3.4.1.GA
```
** BUILD FAILED **
The following build commands failed:
    Ld build/Debug-iphonesimulator/MyApp.app/MyApp normal i386
```

Building with Titanium SDK 3.5.1.GA
```
** BUILD FAILED **
The following build commands failed:
    Ld build/Debug-iphonesimulator/MyApp.app/MyApp normal i386
    Ld build/Debug-iphonesimulator/MyApp.app/MyApp normal x86_64
```
Removing the module fixes the issue.
Any idea why is this happening?

**Comment by pasine** [comment]
FYI I was able to fix the problem using [this fork](https://github.com/TheBookPeople/HockeyApp/tree/ios-sdk-update) of your module that contains the last version of the SDK.

**Comment by Mobilizr** [comment]
I have downloaded the current master, run the build.py script and installed the module. But as soon as I add it to my project (which is using the 3.5.1.GA SDK) then I also get the same Build errors as mentioned above.

Any clues on how to fix this?

**Comment by Mobilizr** [comment]
@pasine any chance you can put the zipped working module somewhere for me to download?

**Comment by timanrebel** [comment]
@pasine Would you be able to create a PR? Unfortunately I'm too busy atm to do it myself

**Comment by pasine** [comment]
@Mobilizr @timanrebel I'll try to sort it out as soon as I can.
Sorry, but I am busy too today.

**Comment by pasine** [comment]
@Mobilizr [here is the module](https://www.dropbox.com/s/iuyszklqj8mas5j/nl.rebelic.hockeyapp-iphone-0.4.4.zip?dl=0). Let me know if it works.
Sorry @timanrebel, I couldn't find the source I used to build it.
I am trying to rebuild it starting from your code, but I think the other module was using a different approach (the two manifests are different).

**Comment by Mobilizr** [comment]
Thanks @pasine ! That is a great start.



I have installed the plugin and it “seems" to be working. I am wondering if the module is missing something as the strings seems to be missing - i.e. I get the system string showing. Not sure if an attachment will work here but will try it.




What do I do to fix this issue?

**Comment by Mobilizr** [comment]
@pasine and also related when I bring up the feedback screen I see the the system strings again, and also the styling is really bad...

![screen shot 2015-05-22 at 3 52 55 am](https://cloud.githubusercontent.com/assets/901045/7757588/2dc31fc8-0036-11e5-976a-6fcaa5d0477f.png)

I am wondering if the module was built and was missing the "HockeySDKResources.bundle" in Xcode? I am just guessing based on other reports such as this one: http://support.hockeyapp.net/discussions/problems/38392-hockeyapp-ios-update-text-is-showing-system-text

Thanks for your help. Really looking forward to getting this working but appreciate people are busy.
