### ISSUE TITLE
Not seeing any crashes reported in HockeyApp

### ISSUE THREAD

**Issue by jtoth55** [timanrebel/HockeyApp#6]
I created new HockeyApp "apps" for both Android and iOS, set the type of each to "Alpha", and specified the appropriate app id. I also created a "version" for each app that matches the versionName and versionCode in the tiapp.xml. I then plugged in the keys into my Ti app.js, using the 2 lines of code in the read me. 

When I launch the app in the iPhone Simulator or Android Genymotion emulator and force a js error, I don't see any crashes in HockeyApp. What am I missing?

**Comment by badrudeen** [comment]
Tim, Did you check with Peerby? 
What are those 2 open source modules they are using - to send JS errors to their server?
