### ISSUE TITLE
Enable adding screenshots to Feedback

### ISSUE THREAD

**Issue by caspahouzer** [timanrebel/HockeyApp#9]
I don't know the HockeyApp API well. So I ask you: Is it possible to take a screenshot of the actual screen and send it with the feedback form?

**Comment by caspahouzer** [comment]
Happy new year. 

Any news on this enhancement? :-)

**Comment by timanrebel** [comment]
Happy new year to you too! 

I have been way to busy, but will try to add it soon. Sorry!

**Comment by caspahouzer** [comment]
:+1:

**Comment by caspahouzer** [comment]
I don't want bother you, but I really need this feature for a customer.

I tried for myself implementing this function with no success. I see the function showFeedbackComposeViewWithGeneratedScreenshot in the new framework, but I'm not able to get it working.

So, if you find some time, that would be really great.

**Comment by timanrebel** [comment]
Let me try to fix it on Monday when I'm back home. 

with kind regards / met vriendelijke groet,




Timan Rebel

**Comment by timanrebel** [comment]
I'm having a hard time compiling the module with the newest version of the HockeyApp SDK. Will keep you posted

**Comment by caspahouzer** [comment]
Thanks you!

**Comment by caspahouzer** [comment]
No stress, switched to Apples Testflight
